"use client"

import Layout from "../components/_layout";
import Footer from "../components/footer";

export default function TermsCondition() {
    return (
        <Layout>

            <section className="BlogBanner py-2">
                <div className="container py-3">
                    <div className="row">
                        <div className="col-12">
                            <h1 className="mb-0 fw-bold color-white text-center">Terms & Conditions</h1>
                        </div>
                    </div>
                </div>
            </section>
            <section className="fs-14 py-5">
                <div className="container">
                    <div className="row">
                        <div className="col-12">
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <p className="mb-0">SHIPRA TRAVELS PVT. LTD. (“Shipra Travels,” “We,” “Us,” or “Our”), The Company That Owns And Operates Travanya, And Its Related Companies, Appreciates Your Trust. We Invite And Welcome Visitors on www.travanya.com Website. The aim Of This Website Is To Assist Customers In Gather Travel Information, Posting Reviews/Opinions On Their Travel Related Experiences / Issues, And Engage Them In Travel Related Forums So That They Gather Maximum Information On The Travel Industry / Countries/ Cities Around The World. By Accessing Or using travanya.com In Any Manner, It Is Considered That You Have Agreed To Be Bound By The Agreement As If You Had Signed This Agreement. Please Read The Agreement Carefully. If You Do Not Accept All Of These Terms And Conditions, Please Do Not Use This Website. We Suggest Visitors Of travanya.com Return To This Page Periodically To Review The Most Current Version Of The Agreement. travanya.com Reserves The Right At Any Time, At Our Sole Discretion, To Change Or Otherwise Modify The Agreement Without Prior Notice, And Your Continued Access Or Use Of This Website Signifies Your Acceptance Of The Updated Or Modified Agreement.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Prices</h2>
                                <p>All Prices Displayed For The Products And Services on travanya.com are Subject To Change Without Prior Information Or Notice And Prices You See While Making The Booking May Not Be Final Until The Full Payment For The Product Or Service Is Made At The End Of The Booking Process.</p>
                                <p className="mb-0">Prices On www.travanya.com shall be inclusive or exclusive of Booking Fee, Hotel Taxes, Airport Taxes, Port Taxes Or Any Other Applicable Government Taxes (GST And VAT), Etc. Availability Of Any Product Or Service Is Subject To Change At Any Point In Time Even While Finalizing The Booking, Which Can Lead To Price Variation, Depending Upon The Basis Of Available Room Type In The Hotel, Flight Booking Class, Cruise Cabin, Etc At That Point In Time.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Booking And Payments</h2>
                                <p>All Online Payments That Happen For Any Of The Products Or Services Booked On www.travanya.com Are Secure. travanya.com Does Not Store The Credit / Debit Or Any Other Payment Card Details Of Any Customer In The Database Or In Any Data Backup System. Once You Are Ready To Transact You Are Transferred Directly To the Bank Website. The Card Details Are Captured On The Bank Website and not in travanya.com. travanya.com Takes No Responsibility, In Case Of Any Misuse Of Credit Cards By Whomsoever.</p>
                                <p>Shipra Travels Pvt Ltd acts as an Agent For Its Third Party Providers And Distributors For All Products And Services Purchased By You On This Website. You May Place Bookings For Or May Make Purchases Of Products And Services Online At This Site. A Contract For The Sale And Purchase Of Products And Services May Be Made Online At This Site By Your Acceptance Of The Products And Services Offered On The Site (The “Contract”) By Third Party Providers And/Or Distributors And/Or Where Stated, Shipra Travels Pvt Ltd, And You Hereby Agree To Waive Any Rights To Challenge The Validity Or Enforceability Of Contracts Entered Into On This Site On The Grounds That It Was Made In Electronic Form Instead Of By Paper And/Or Signed Or Sealed. Please Note That By Indicating Your Acceptance To Purchase Any Product Or Service Offered On The Website, You Are Obligated To Complete Such Transactions. You Are Prohibited From Indicating Your Acceptance To Purchase Products And Services Where You Do Not Intend To Complete Such Transactions. You May Not Purchase Goods Or Services That You Are Prohibited From Purchasing Or Possessing By Any Applicable Indian Or Local Laws. The Responsibility For Ensuring Compliance With All Applicable Laws Shall Be Yours Alone. By Submitting An Order To Purchase Goods Or Services, You Represent And Warrant That You Have The Legal Right To Purchase, Utilise And/Or Possess Such Goods Or Services.</p>
                                <p>In Case Any User Is Booking A Ticket/Hotel Or Any Other Online Services Via A Credit/Debit/Gift Card Which Is Not Directly In The Name Of The Person Availing These Services – Shipra Travels Pvt Ltd Reserves The Right To Cancel/Hold The Said Service Till The Time Proper Verification Is Provided. In Case You Are Booking Using Someone Else`s Credit/Debit/Gift Card – You Are Requested To Send Us A Copy Of The Card Used (At The Following Email ID: info@travanya.com) A Photo Identification Card Of The Person In Whose Name The Card Is, As Well As The Person In Whose Name The Services Are Being Provided And An Authority Letter From The Said Credit/Debit/Gift Card Holder.</p>
                                <p className="mb-0">In Case Any Of The Above Mentioned Conditions Are Not met, travanya.com Reserves The Right To Declare Such Transactions As Fraudulent And Cancel/Hold The Service Provided. It Also Holds The Right To Charge The Requisite Cancellation Charges That May Be Applicable Before Refunding Any Such Amount.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Amendment To Booking & Purchase</h2>
                                <p className="mb-0">Kindly Read And Note The Terms & Conditions For Amendment In Bookings And Purchases, While Making The Booking Or Purchase, Which May Vary For Each Product And Service. If You Don’t Find Any Terms And Conditions Regarding The Amendment Policy, You May NOT Change Your Booking Or Purchase Online. Kindly Call Our Customer Care Team To Know The Amendment Policy And Do The Necessary Amendment.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Cancellation & Refunds</h2>
                                <p>Cancellation Of Bookings And Cancellation Policy Differs For Each Product OR Service. When You Make A Booking, Kindly View Terms & Conditions Of Each Product OR Service, Which Reflects The Cancellation, Refund With Booking Terms & Conditions. You Can Cancel The Purchased Product Or Service Online On Our Website – www.travanya.com. If You Find Difficulty In Cancelling, You Can Get The Same Cancelled By Calling Our Customer Care Team. Cancellation At Your Request May Require A Minimum Processing Time, Subject To Specific Terms And Conditions Applicable To The Type Of Product Or Service Booked & Purchased.</p>
                                <p>You Can Cancel The Purchased Product Or Service Online On Our Website – www.travanya.com. If You Find Difficulty In Cancelling, You Can Get The Same Cancelled By Calling Our Customer Care Team. Cancellation At Your Request May Require A Minimum Processing Time, Subject To Specific Terms And Conditions Applicable To The Type Of Product Or Service Booked & Purchased.</p>
                                <p>There May Be Full Cancellation Penalty On The Products Or Services Booked And Purchased, Which Are Non-Utilized Or Cancelled After The Cancellation Deadline Mentioned In The Terms And Conditions, While Making The Purchase.</p>
                                <p>You Agree To Bear The Full Cost Of Any Booking, Cancellation And Administration Fees For Any Products Or Services Booked But Not Utilized For Any Reason. In Some Cases, travanya.com may Charge Cancellation Or Amendment Fees In Addition To Those Imposed By Travel Services Providers.</p>
                                <p>www.travanya.com Reserves The Right To Decline Any Booking Or Purchase For Any Reason And Shall Not Be Held Liable For Any Resulting Claims Of Losses, Damages Or Compensation. In Such An Event, travanya.com shall Refund To You All un utilised Money Collected From You For That Purchase.</p>
                                <p>For Bookings And Purchases, Which Has Already Been Paid By You, When Cancelled, Refunds Will Be Made (Based On The Refund Policy, Mentioned In Terms And Conditions, While Making The Booking Or At The Time Of Purchase). For Air Ticket, It May Take Between 30-45 Working Days And For The Hotels It May Take Between 10-15 Working Days For The Amount To Get Credited Into Your Account. Refund Policy May Vary For Every Product And Service.</p>
                                <p className="mb-0">The Preceding Refund Timeline Is A Guide For Your Reference Only And Shall Not Be Binding Upon travanya.com.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Duplicate Bookings</h2>
                                <p className="mb-0">You Agree That Multiple Duplicate Bookings For The Same Traveller(s) Are Not Allowed And May Result In Damage And Loss To travanya.com Which You Will Bear In Full.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Products & Services</h2>
                                <p>Products & Services Statements On This Website Are For General Description Purposes Only And Not All The Products Or Services Are Available In Every State Or Country. You Can Send Us An enquiry By Clicking Our Contact Us Or Send Query Section, We Will Provide You With The Details Regarding Terms & Conditions, Exclusions, Products And Services Applicable For You. Please Note The Products And Services That Can Be Booked And Purchased On The Website</p>
                                <p>1: Hotels -When You Make A Hotel Booking On The Website, Kindly Go Through The Fact Sheet With Terms And Conditions Carefully To Ensure The Amenities Present In The Hotel Or The Category Of The Hotel Is As Per Your Requirement. travanya.com Keeps Updating The Fact Sheets With Terms And Conditions Of The Hotels, However It Is Dependent On The Hotel To Provide Us With The Updated Information. Renovation At Hotels Is Normally Undertaken At Sole Discretion Of Hotels And Not Necessarily Is Informed To Us. In Case Of Any Disputes, travanya.com shall not be held Liable For Any Disruption In Information.</p>
                                <p>2: Sightseeing Tours -There Is A Choice Of Seat In Coach (SIC) Sightseeing And Private Sightseeing Tours. Seat In Coach Tours / Transfers May Have A Waiting Time At The Airport / Hotels. Seat In Coach Tours Are As Per The Fixed Timings And Does Not Allow You To Stop At Any Site Of Interest To You, Which Are Not A Part Of The Program, As Seat In Coach Tours Are Fixed With A Schedule. You Have To Make A Choice According To Your Requirement And Budget. Entrance Fees At The Monuments Or Places Of Interest Are Not Included In The Sightseeing Tours Unless And Until Specified.</p>
                                <p>3: Airlines -There Is A Choice To Book Low Cost Airlines And Full Service Airlines Options. Low Cost Airlines Do Not Have All The Services On Board In The Flight, So Kindly Choose The Airlines Carefully And Please Read The Terms & Conditions / Cancellation Policy Before Making Any Purchase Of The Airlines Ticket. There Are Paper Tickets / E-Tickets That Will Be Issued To You And Both Are Valid To Travel By The Airlines. With E-Tickets, There Is A Mandatory Requirement Of Original Identity Photo Card For You To Carry And Show At The Check-In Counter Of The Airport. travanya.com Is Only An Intermediary Party And Hence Takes No Responsibility In Case Of Any Delay, Change In Route Or Cancellation In The Flight Due To Any Reasons.</p>
                                <p>4: Holidays -Kindly Read The Terms & Conditions With The Inclusions, Package Itinerary And Other Details Before Making Any Purchase Of The Holiday Packages. In Case If The Package Is Not As Per Your Requirement Or Suits Your Needs, We Can Also Customize The Same For You. Kindly Click On The Send Query Of The Website With All The Details Like Hotel Category, No. Of Nights, No. Of Pax, Destinations Would Like To Visit, Etc And Our Customer Care Team Will Get Back To You With The Package</p>
                                <p>5: Car Rental (Self Drive Or Chauffeur Drive) -Please Read The Terms & Conditions Before Making Any Purchase Of This Service. travanya.com Takes No Responsibility In Case Of Any Break Down Of The Car Or The Quality Of Car Is Not Up To The Level And Delays Due To Bad Traffic Conditions, Any Penalty Due To Speed By The Driver Or By Yourself, Etc.</p>
                                <p className="mb-0">6: Travel Insurance -travanya.com Strongly Recommends Insurance Cover And Safety For All The Traveller/S Travelling Domestic Or Outside The Country. Traveller/S Can Purchase The Travel Insurance On The Website. Please Read The Terms And Conditions Given By The Insurance Provider Before Issuing The Same. travanya.com Takes No Responsibility And Liability On The Claims And Disputes Whatsoever As Mentioned By The Insurance Provider.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Delivery Of Products & Services</h2>
                                <p>1: Hotels -When A Hotel Booking Is Made And Purchased On The Website, It Gives An Instant Confirmation After The Payment Is Made Completely And You Will Receive The Hotel Confirmation Voucher In Your Mentioned Email Id. Voucher Give Details About The Hotel Address, Telephone Number, Hotel Confirmation Number, Meal Plan, Payment Details, Supplier Details, Other Relevant Important Information Etc. Voucher Is To Be Given To The Hotel At The Check-In Counter.</p>
                                <p>2: Sightseeing Tours -When A Sightseeing Tour Is Booked And Purchased Online, An Instant Confirmation Voucher Is Issued And You Will Receive The Same In Your Mentioned Email Id After The Payment Is Made Completely. Voucher Gives Details About The Pick-Up Time, Pick-Up Point, Date Of The Sightseeing Tour, Supplier Details, Payment Details, Other Relevant Important Information Etc. There Is A Choice Of Seat In Coach (SIC) Sightseeing And Private Sightseeing Tours. Seat In Coach Tours / Transfers May Have Waiting Time At The Airport / Hotels.</p>
                                <p>3: Airlines E-Tickets -An E-Ticket Is A Paperless Electronic Document With A Unique Confirmation Number Given To Passengers In Place Of Paper Ticket. Passengers Are Required To Produce The Unique Confirmation Number Print-Out At The Airlines Check-In Counter To Get The Boarding Pass. How To Receive An E-Ticket?After The Complete Payment Is Made Online Via Credit / Debit Or Any Other Payment Card, Your E-Ticket Details Will Be Mailed To You At Your Email Address Mentioned At The Time Of Making The Purchase. In Case If You Don’t Have An Email Address, The Details Will Be Given To You Over The Phone Or You Can Come To Pick Up Your E Ticket From Our Office Or Directly From The Airlines Counter At The Airport By Giving Them The Unique Confirmation Number – PNR</p>
                                <p>4: Paper Tickets -Some Of The Airlines Are Still Issuing Paper Tickets. You Will Receive The Booking Confirmation Number Immediately After You Have Made Full Payment Online. All The Paper Tickets Will Be Dispatched To The Delivery Address Mentioned At The Time Of Making The Purchase. It Takes 3 Working Days To Receive The Paper Ticket At Your Address From The Day Of Making The Purchase. travanya.com would Not Be Responsible In Case If The Customer Is Not Present At The Address At The Time Of Delivery</p>
                                <p>5: Holidays -Holiday Packages Takes Minimum 24 Hours In Getting The Confirmation, Once The Payment Is Made Online On The Website, Our Customer Care Team Will Get In Touch With You And Will Mail You The Confirmation Vouchers Along With The Day To Day Program At The Email Address Mentioned By You At The Time Of Making The Purchase Or In Case If There Is No Email ID, Vouchers Will Be Delivered At Your Address Within 3 Working Days At No Additional Cost. travanya.com would Not Be Responsible In Case If The Customer Is Not Present At The Address At The Time Of Delivery.</p>
                                <p>6: Rail And Cruises -When A Rail Or Cruise Booking Is Made And Purchased On The Website, It Gives An Instant Confirmation After The Payment Is Made Completely And You Will Receive The Rail Confirmation Ticket Or Cruise Voucher In Your Email Id Mentioned At The Time Of Making The Purchase . If You Don’t Have An Email Id, You Can Call Our Customer Care Team And Can Get The Same Collected From Our Office Or It Can Also Be Delivered At Your Doorstep At An Additional Cost.</p>
                                <p>7: Car Rental (Self Drive Or Chauffeur Drive) -It Takes Minimum 4 – 5 Hours For The Car Rental Confirmation. Once The Payment Is Made Online, Our Customer Care Team Will Get In Touch With You And Give You The Confirmation Details Over The Phone And Will Also Email You The Confirmation Voucher.</p>
                                <p>8: Travel Insurance -Travel Insurance Policy Will Be Issued And Mailed To You Instantly At An Email Id Given At The Time Of Making The Purchase. In Case If You Don’t Have An Email Id, You Can Get The Details From Our Customer Care Team And Same Can Be Collected From Our Office Or Can Be Delivered At Your Doorstep At An Additional Cost. Third Party Travel Service Providers</p>
                                <p>You May Be Bound By Terms And Conditions Imposed By The Travel Service Providers For Whom travanya.com acts As An Agent Including Conditions Of Carriage, Refund And Cancellation Policies Of Airlines, Cruise Lines, Car Rental Companies, Hotels, Vacation Rentals, Etc.</p>
                                <p className="mb-0">travanya.com Is Not Liable For Any Claims Against Non-Fulfilment Or Unsatisfactory Fulfilment Of Products And Services Purchased On Your Behalf By travanya.com From These Third Party Providers And Distributors, Such As, But Not Limited To, Airlines, Hotels, Tour Operators, Car Rental Companies, Insurance Companies, And Other Entities. Sometimes, Hotels, When They Are In A Overbooking Situation, They Move The Booked Passengers To Some Other Hotel And Also With The Airlines And Other Service Providers May Overbook Passengers On Their Flights Or Re-Schedule Flight Times, In Such Incidents travanya.com Takes No Responsibility And Should Not Be Liable For Any Looses, Damages That May Take Place Due To The Above Situation</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Terms & Conditions For Product & Services</h2>
                                <p className="mb-0">Some Of The Products And Services Have Special Governing Terms & Conditions, Which Shall Apply In Addition To The Terms And Conditions Mentioned Separately For Each Product And Service. It Is Important That You Read The Obtain The Information Related To These Specific Products And Services As They May Contain Exclusions Of Limitations Of Liability And Other Terms And Conditions, Including Restrictions On Amendment Or Cancellation. Some Of These Terms And Conditions For Specific Products And Services Shall Include Terms And Conditions Found On Your Screens And When Using Any Part Of This Website.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Jurisdiction</h2>
                                <p className="mb-0">In The Event Of Any Dispute, The Dispute Shall Be Referred To The Sole Arbitrator To Be Appointed By travanya.com In Chandigarh And The Matter Shall Be Subjected To The Jurisdiction Of Chandigarh Courts Only.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Passport, Visa & Health Requirement</h2>
                                <p>It Is Mandatory Requirement For Most Of The Countries; Foreign Nationals Coming Into The Country Must Hold Passport With A Validity Of Minimum 06 Months. Visa And Health Regulations Are Different From Country To Country. It Is The Sole Responsibility Of An Individual Traveller To Ensure The Submission Of Complete Documentation And Medical Requirements To The Country Embassy / Consulate They Are Visiting. travanya.com Takes No Responsibility In Any Rejections Or Declining Of The Visa Issuance Due To Any Reasons.</p>
                                <p className="mb-0">travanya.com Reserves The Right To Decline Any Booking Or Purchase For Any Reason And Shall Not Be Liable For Any Resulting Claims For Losses, Damages Or Compensation. In Such An Event, travanya.com shall Refund To You All The Unutilised Payment Collected After Deducting The Booking Fee / Administration Charges / Cancellation Charges (If Applicable) For That Purchase.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Content Submission</h2>
                                <p>travanya.com , Enable Users To Submit, Post, Exchange, Transmit Or Make Available For Inclusion Information, Ideas, Opinions, Images, Photos Or Other Materials (Collectively “Content”). You Agree That Responsibility For All The Content Made Posted Or Available On travanya.com is Your Responsibility. travanya.com , Its Partners, Affiliates, Subsidiaries Or Employees Shall In No Way Be Held Liable And Responsible For Any Content Posted By You Or Any Third Party. travanya.com At Its Discretion Can Refuse To Post Or Remove The Contents Posted By You For Any Reason Including, Without Limitation, Violation Of These Terms Or If It Is Otherwise Deemed To Be Unlawful Or Objectionable.</p>
                                <p>When The Content Is Posted By You, You Give Permission Without Any Charges To travanya.com An Unrestricted License To Use, Copy, Modify, Reformate, Translate, Display Publically, Republish Whole Or Part Of The Content For Any Purpose Of Commercial Use Or In Connection With Any Other Services Offered Or In Promotion By travanya.com</p>
                                <p>You Also Confirm That You Have All Rights To License The Content You Posted On The Website For The Purposes Mentioned Above.</p>
                                <p>Use Of The Website -Visitors / Users Of This Website Hereby Agree Upon Following Terms.</p>
                                <p>Information/ Experience Posted By You On travanya.comIs True, Accurate, Current And Complete And It Is Not A Biased Opinion For Any Reason Due To Personal Enmity</p>
                                <p>If You Have A HB Account, You Will Safeguard Your Account Information And Will Supervise And Be Completely Responsible For Any Use Of Your Account By Anyone Other Than You.</p>
                                <p className="mb-0">You Must Be 13 Years Of Age Or Older In Order To Register For An Account And Contribute To Our Website. HB Does Not Knowingly Collect The Information Of Anyone Under The Age Of 13. HB Retain Sole Right And Has Sole Discretion To Deny Access To Anyone To This Website And The Services We Offer, At Any Time And For Any Reason, Including, But Not Restricted To, For Violation Of This Agreement.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Prohibited Activities On The Site</h2>
                                <p>The Content And Information Related To Messages, Data, Information, Text, Music, Sound, Photos, Graphics, Video, Maps, Icons, Software, Code Or Other Material On This Website, As Well As The Infrastructure Used To Provide Such Content And Information, Becomes Proprietary Rights Of travanya.com . You Agree That The Information Posted By You Is True And Complete To Your Knowledge And Is Not Biased. You Also Agree Not To:</p>
                                <ol>
                                    <li className="my-1">Use This Website Or Its Contents For Any Commercial Purpose;</li>
                                    <li className="my-1">Access, Monitor Or Copy Any Content Or Information Of This Website Using Any Robot, Spider, Scraper Or Other Automated Means Or Any Manual Process For Any Purpose Without Our Written Permission</li>
                                    <li className="my-1">Violate The Restrictions In Any Robot Exclusion Headers On This Website Or Bypass Or Circumvent Other Measures Employed To Prevent Or Limit Access To This Website</li>
                                    <li className="my-1">Take Any Action That Imposes, Or May Impose, In Our Discretion, An Unreasonable Or Disproportionately Large Load On Our Infrastructure;</li>
                                    <li className="my-1">Deep-Link To Any Portion Of This Website For Any Purpose Without Our Express Written Permission; Or</li>
                                    <li className="my-1">“Frame”, “Mirror” Or Otherwise Incorporate Any Part Of This Website Into Any Other Website Without Our Prior Written Authorization.</li>
                                    <li className="my-1">Attempt To Modify, Translate, Adapt, Edit, Decompile, Disassemble, Or Reverse Engineer Any Software Programs Used By travanya.comIn Connection With The Website Or The Services</li>
                                </ol>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Reviews, Comments</h2>
                                <p>travanya.com Aim Is To Update Travellers By Real Time Experiences Of Other Travellers. We Are Thankful To Our Visitors For Writing Their Experiences On This Site. Please Be Informed That After Posting Content On This Website By Any Way, Including Any Review, Questions, Comments, Suggestions, Ideas Etc., You Grant travanya.com And Its Affiliates A Non-exclusive, Royalty-Free, Perpetual, Transferable, Irrevocable And Fully Sub Licensable Right To (A) Use, Reproduce, Modify, Adapt, Translate, Distribute, Publish, Create Derivative Works From And Publicly Display And Perform Such Submissions Throughout The World In Any Media And (B) Use The Name That You Submit In Connection With Such Submissions. You Acknowledge That travanya.com May Choose To Provide Attribution Of Your Comments Or Reviews At Our Discretion. You Further Grant travanya.com The Right To Pursue At Law Any Person Or Entity That Violates Your Or travanya.com Rights In The Submissions By A Breach Of This Agreement. You Also Acknowledge And Agree That All Content Submitted / Posted On The Website By You Are Non-Confidential And Non-Proprietary Once It Is Posted. travanya.com Has Just Provided Interactive Areas On The Site As A Platform For Discussions But At The Same Time All The Visitors Of travanya.com Are Solely Responsible For Use Of Interactive Areas Of The Site And Are Using At Their Own Risk</p>
                                <p>Any Message, Data, Information, Content , Music, Sound, Photos, Graphics, Code Or Any Other Material That Is Unlawful, Libelous, Defamatory, Obscene, Pornographic, Indecent, Lewd, Suggestive, Harassing, Threatening, Invasive Of Privacy Or Publicity Rights, Abusive, Inflammatory, Fraudulent Or Otherwise Objectionable;</p>
                                <p>Content That Would Constitute, Encourage Or Provide Instructions For A Criminal Offense, Violate The Rights Of Any Party, Or That Would Otherwise Create Liability Or Violate Any Local, State, National Or International Law</p>
                                <p>Content That May Infringe Any Patent, Trademark, Trade Secret, Copyright Or Other Intellectual Or Proprietary Right Of Any Party;</p>
                                <p>Content That Impersonates Any Person Or Entity Or Otherwise Misrepresents Your Affiliation With A Person Or Entity, Including travanya.com.</p>
                                <p>Unsolicited Promotions, Political Campaigning, Advertising, Contests, Raffles, Or Solicitations;</p>
                                <p>Private Information Of Any Third Party, Including, Without Limitation, Surname (Family Name) Addresses, Phone Numbers, Email Addresses, Social Security Numbers And Credit Card Numbers;</p>
                                <p>Viruses, Corrupted Data Or Other Harmful, Disruptive Or Destructive Files;</p>
                                <p>Content That Is Unrelated To The Topic Of The Interactive Area(S) In Which Such Content Is Posted; Or</p>
                                <p>Content Or Links To Content That, In The Sole Judgment Of travanya.com , (A) Violates The Previous Subsections Herein, (B) Is Objectionable, (C) Which Restricts Or Inhibits Any Other Person From Using Or Enjoying The Interactive Areas Or The Site, Or (D) Which May Expose travanya.com Or Its Affiliates Or Its Users To Any Harm Or Liability Of Any Type.</p>
                                <p>travanya.com Takes No Responsibility And Assumes No Liability For Any Content Posted, Stored Or Uploaded By You Or Any Visitors / Third Party, Or For Any Loss Or Damage Thereto, Nor Is travanya.com Liable For Any Mistakes, Defamation, Slander, Libel, Omissions, Falsehoods, Obscenity, Pornography Or Profanity You May Encounter.</p>
                                <p>travanya.com Has Just Provided An Interactive Platform And Is Not Liable For Any Statements, Representations Or Content Provided By Its Users In Any Public Forum, Personal Home Page Or Other Interactive Area.</p>
                                <p>travanya.com Reserves The Sole Right To Remove, Screen Or Edit Without Notice Any Content Posted Or Stored On The Site At Any Time And For Any Reason, And You Are Solely Responsible For Creating Backup Copies Of And Replacing Any Content You Post Or Store On The Site At Your Sole Cost And Expense.</p>
                                <p>If It Is Determined That You Retain Moral Rights (Including Rights Of Attribution Or Integrity) In The Content, You Hereby Declare That (A) You Do Not Require That Any Personally Identifying Information Be Used In Connection With The Content, Or Any Derivative Works Of Or Upgrades Or Updates Thereto; (B) You Have No Objection To The Publication, Use, Modification, Deletion And Exploitation Of The Content By travanya.com Or Its Licensees, Successors And Assigns; (C) You Forever Waive And Agree Not To Claim Or Assert Any Entitlement To Any And All Moral Rights Of An Author In Any Of The Content; And (D) You Forever Release travanya.com, And Its Licensees, Successors And Assigns, From Any Claims That You Could Otherwise Assert Against travanya.com By Virtue Of Any Such Moral Rights.</p>
                                <p className="mb-0">Any Use Of The Interactive Areas Or Other Portions Of The Site In Violation Of The Foregoing Violates These Site Terms And May Result In, Among Other Things, Termination Or Suspension Of Your Rights To Use The Interactive Areas And/Or The Site. In Order To Cooperate With Legitimate Governmental Requests, Subpoenas Or Court Orders, To Protect travanya.com Systems And Customers, Or To Ensure The Integrity And Operation Of travanya.com Business And Systems, travanya.com May Access And Disclose Any Information It Considers Necessary Or Appropriate, Including, Without Limitation, User Profile Information (I.E. Name, Email Address, Etc.), IP Addressing And Traffic Information, Usage History, And Posted Content. shipratravel Bag’s May Right To Disclose Any Such Information Shall Take Precedence Over Any Terms Of shipratravel Bag’s Privacy Policy. travanya.com Suggest To All Its Visitors And Users Of The Site / Passengers To Investigate And Whether Review / Content Placed Is Correct Or Just An Opinion. travanya.com Will Not Be Responsible For Any Wrong Information Placed On The Site IS NOT ACCOUNTABLE FOR DAMAGES OR LOSSES THAT MAY RESULT FROM TRAVEL TO SUCH DESTINATIONS.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Liability Disclaimer</h2>
                                <p>THE CONTENT, INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES PUBLISHED ON THIS WEBSITE MAY INCLUDE INACCURACIES OR ERRORS travanya.com, ITS SUBSIDIARIES / PARENT COMPANY AND CORPORATE AFFILIATES, DO NOT GUARANTEE THE ACCURACY OF, AND DISCLAIM ALL LIABILITY FOR ANY ERRORS OR OTHER INACCURACIES RELATING TO THE INFORMATION AND DESCRIPTION OF THE HOTEL, AIR, CRUISE, CAR AND ANY OTHER TRAVEL PRODUCTS DISPLAYED ON THIS WEBSITE (INCLUDING, WITHOUT LIMITATION, THE PRICING, PHOTOGRAPHS, LIST OF HOTEL AMENITIES, GENERAL PRODUCT DESCRIPTIONS, ETC.).</p>
                                <p>travanya.com MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF THE INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES CONTAINED ON THIS WEBSITE FOR ANY PURPOSE, AND THE INCLUSION OR OFFERING OF ANY PRODUCTS OR SERVICES ON THIS WEBSITE DOES NOT CONSTITUTE ANY ENDORSEMENT OR RECOMMENDATION OF SUCH PRODUCTS OR SERVICES BY THE travanya.com. ALL SUCH INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND. travanya.com DISCLAIM ALL WARRANTIES AND CONDITIONS THAT THIS WEBSITE, ITS SERVERS OR ANY EMAIL SENT FROM travanya.com, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. travanya.com HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO THIS INFORMATION, SOFTWARE, PRODUCTS, AND SERVICES, INCLUDING ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON INFRINGEMENT.</p>
                                <p>IN NO EVENT SHALL travanya.com (ITS OFFICERS, DIRECTORS AND AFFILIATES/ PARTNERS) BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, YOUR ACCESS TO, DISPLAY OF OR USE OF THIS WEBSITE OR WITH THE DELAY OR INABILITY TO ACCESS, DISPLAY OR USE THIS WEBSITE (INCLUDING, BUT NOT LIMITED TO, YOUR RELIANCE UPON OPINIONS APPEARING ON THIS WEB SITE; ANY COMPUTER VIRUSES, INFORMATION, SOFTWARE, LINKED SITES, PRODUCTS, AND SERVICES OBTAINED THROUGH THIS WEBSITE; OR OTHERWISE ARISING OUT OF THE ACCESS TO, DISPLAY OF OR USE OF THIS WEBSITE) WHETHER BASED ON A THEORY OF NEGLIGENCE, CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, AND EVEN IF travanya.com HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
                                <p className="mb-0">The Limitation Of Liability Reflects The Allocation Of Risk Between The Parties. The Limitations Specified In This Section Will Survive And Apply Even If Any Limited Remedy Specified In These Terms Is Found To Have Failed Of Its Essential Purpose. The Limitations Of Liability Provided In These Terms Inure To The Benefit Of travanya.com .</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Indemnification</h2>
                                <p>You Agree To Defend And Indemnify travanya.com And Its Affiliates And Any Of Their Officers, Directors, Employees And Agents From And Against Any Claims, Causes Of Action, Demands, Recoveries, Losses, Damages, Fines, Penalties Or Other Costs Or Expenses Of Any Kind Or Nature Including But Not Limited To Reasonable Legal And Accounting Fees, Brought By Third Parties As A Result Of:</p>
                                <ol>
                                    <li className="my-2">Your Breach Of This Agreement Or The Documents Referenced Herein;</li>
                                    <li className="my-2">Your Violation Of Any Law Or The Rights Of A Third Party; Or</li>
                                    <li className="my-2">Your Use Of This Website.</li>
                                </ol>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Links To Third-Party Sites</h2>
                                <p className="mb-0">This Website May Contain Hyper links To Websites Operated By Parties Other Than travanya.com . Such Hyper links Are Provided For Your Reference Only. We Do Not Control Such Websites And Are Not Responsible For Their Contents Or The Privacy Or Other Practices Of Such Websites.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Currency Converter</h2>
                                <p className="mb-0">Currency Rates Are Based On Various Publicly Available Sources And Should Be Used As Guidelines Only. Rates May Not Be Verified As Accurate, And Actual Rates May Be Different From What Is Being Displayed. The Information Supplied By This Application Is Believed To Be Accurate, But travanya.com , And/Or Its Affiliates Do Not Warrant Or Guarantee Such Accuracy. When Using This Information For Any Financial Purpose, We Advise You To Consult A Qualified Professional To Verify The Accuracy Of The Currency Rates. We Do Not Authorize The Use Of This Information For Any Purpose Other Than Your Personal Use And You Are Expressly Prohibited From The Resale, Redistribution, And Use Of This Information For Commercial Purposes.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Copyright And Trademark Notices</h2>
                                <p>All Contents Of This Website Are 2014 travanya.com All Rights Reserved. travanya.com Is Not Responsible For Content On Websites Operated By Parties Other Than travanya.com. travanya.com, Logo And travanya.com Family – Cartoon Characters And All Other Product Or Service Names Or Slogans Displayed On The Site Are Registered And/Or Common Law Trademarks Of travanya.com, And/Or Its Suppliers Or Licensors, And May Not Be Copied, Imitated Or Used, In Whole Or In Part, Without The Prior Written Permission Of travanya.com Or The Applicable Trademark Holder. In Addition, The Look And Feel Of The Site, Including All Page Headers, Custom Graphics, Button Icons And Scripts, Is The Service Mark, Trademark And/Or Trade Dress Of travanya.com And May Not Be Copied, Imitated Or Used, In Whole Or In Part, Without The Prior Written Permission Of travanya.com. All Other Trademarks, Registered Trademarks, Product Names And Company Names Or Logos Mentioned In The Site Are The Property Of Their Respective Owners. Reference To Any Products, Services, Processes Or Other Information, By Trade Name, Trademark, Manufacturer, Supplier Or Otherwise Does Not Constitute Or Imply Endorsement, Sponsorship Or Recommendation Thereof By travanya.com.</p>
                                <p>Other Logos And Product And Company Names Mentioned Herein May Be The Trademarks Of Their Respective Owners.</p>
                                <p>If You Are Aware Of An Infringement Of Either Your Brand Or Our Brand, Please Let Us Know By E-Mailing Us At info@travanya.com.</p>
                                <p>You Agree That All Claims You May Have Against travanya.com Arising From Or Relating To The Site Must Be Heard And Resolved In A Court Of Competent Subject Matter Jurisdiction Located In Chandigarh India. Use Of This Website Is Unauthorized In Any Jurisdiction That Does Not Give Effect To All Provisions Of These Terms And Conditions, Including, Without Limitation, This Paragraph.</p>
                                <p>You Agree That No Joint Venture, Agency, Partnership, Or Employment Relationship Exists Between You And travanya.com And/Or Affiliates As A Result Of This Agreement Or Use Of This Website.</p>
                                <p>Our Performance Of This Agreement Is Subject To Existing Laws And Legal Process, And Nothing Contained In This Agreement Limits Our Right To Comply With Law Enforcement Or Other Governmental Or Legal Requests Or Requirements Relating To Your Use Of This Website Or Information Provided To Or Gathered By Us With Respect To Such Use. To The Extent Allowed By Applicable Law, You Agree That You Will Bring Any Claim Or Cause Of Action Arising From Or Relating To Your Access Or Use Of This Website Within Two (2) Years From The Date On Which Such Claim Or Action Arose Or Accrued Or Such Claim Or Cause Of Action Will Be Irrevocably Waived.</p>
                                <p>If Any Part Of This Agreement Is Determined To Be Invalid Or Unenforceable Pursuant To Applicable Law Including, But Not Limited To, The Warranty Disclaimers And Liability Limitations Set Forth Above, Then The Invalid Or Unenforceable Provision Will Be Deemed Superseded By A Valid, Enforceable Provision That Most Closely Matches The Intent Of The Original Provision And The Remaining Provisions In The Agreement Shall Continue In Effect.</p>
                                <p>This Agreement (And Any Other Terms And Conditions Referenced Herein) Constitutes The Entire Agreement Between You And travanya.com With Respect To This Website And It Supersedes All Prior Or Contemporaneous Communications And Proposals, Whether Electronic, Oral, Or Written, Between The Customer And travanya.com with Respect To This Website. A Printed Version Of This Agreement And Of Any Notice Given In Electronic Form Shall Be Admissible In Judicial Or Administrative Proceedings Based Upon Or Relating To This Agreement To The Same Extent And Subject To The Same Conditions As Other Business Documents And Records Originally Generated And Maintained In Printed Form.</p>
                                <p>Fictitious Names Of Companies, Products, People, Characters, And/Or Data Mentioned On This Website Are Not Intended To Represent Any Real Individual, Company, Product, Or Event.</p>
                                <p className="mb-0">Any Rights Not Expressly Granted Herein Are Reserved.</p>
                            </div>
                            <div className="bg-light-blue p-3 border border-orange my-3">
                                <h2 className="fw-bold fs-20 color-orange">Service Help</h2>
                                <p className="mb-0">For Answers To Your Questions, You Can Write To Us At: info@travanya.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <Footer></Footer>
        </Layout>
    )
}
